### ISSUE TITLE
How do you personally check whether the installed plugin is working inside of vim?

### ISSUE THREAD

**Issue by aalliikk** [chiphogg/dotfiles#2]
I'm very new to the vim World, so I apologize for being new in this environment. 

One question though: 

How do you personally check whether the installed plugin is working inside of vim?

I installed https://vimawesome.com/plugin/autocomplete-swift which can be outdated, but the Vundle installed it without any errors and warning! But the autocomplete still is not working. 

How to make sure where the problem is? Is there any "for sure" way to do such things?

**Comment by chiphogg** [comment]
Hello, and welcome to the vim world!  🙂 

Unfortunately, plugins are generally pretty ad hoc.  They're each really just a bunch of scripts that get added to the `runtimepath`.  So, I don't really have a "general" way of checking whether a plugin is installed, other than trying to do what the plugin does.

Sometimes, it may raise an error.  You can try entering the `:messages` command in vim to see any warnings or errors that may have scrolled past.

But I have no experience with this particular plugin, and I've migrated away from vundle since it's no longer maintained.

Good luck!

**Comment by aalliikk** [comment]
> Hello, and welcome to the vim world! 🙂

Thank you very much for such a wonderful welcoming message, I really appreciate it and it brightened my day, great! 

I see your point, and if you are not using Vundle anymore, what is your current go-to solution to install the plugins and whatnot? 

Thanks!

**Comment by chiphogg** [comment]
I really like vim-plug (https://github.com/junegunn/vim-plug).  It's similar to vundle, but with better features, and actively maintained.  For example, it fetches all of your plugins _in parallel_, so if you have way too many of them (as I do :wink:), you won't be waiting overly long.  It also lets you pin plugins to a specific version, which can be useful when a vim plugin pushes up a broken version to their `master` branch (not unheard of).
